### ISSUE TITLE
Add auto generation of images via action

### ISSUE THREAD

**Issue by chadmf** [redhat-adsa/agility-map#3]
test adding:
https://github.com/Burnett01/actions-drawio

```yaml
  steps:
  - uses: actions/checkout@v2
  - name: Convert digramm to png
    uses: Burnett01/actions-drawio@1.0
    with:
      src: diagramm.drawio
      dest: diagramm.png
```
